### ISSUE TITLE
Reports that feature comments should be able to direct you to the comment chain

### ISSUE THREAD

**Issue by TheFleetCommander** [hellopaint-io/hellopaint#38] opened 2023-04-21 13:55 UTC
Current: People can report comments on HP, and the comment shows up in the details of the report. However, it is only the reported comment. Moderators are currently missing context around the rest of the comment chain.

Expected: I should be able to click somewhere on the report to be redirected to the comment inside the comment chain on the actual profile or gallery post

**Comment by lucasmerlin** [comment] 2023-04-24 20:52
Duplicate of #13

**Closed as completed by lucasmerlin** 2023-04-24 20:52 UTC
Labels: duplicate, enhancement, moderation, hellopaint

**Comment by TheFleetCommander** [comment] 2023-04-24 21:11
> Duplicate of #13

#13 only addresses Hellopaint, not malmal. Either keep this open and change the tags, or update the other issue to cover both applications
